name: C:\Users\ashwi\anaconda\envs\agri
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - ca-certificates=2024.7.2=haa95532_0
  - openssl=3.0.15=h827c3e9_0
  - pip=24.2=py39haa95532_0
  - python=3.9.19=h1aa4202_1
  - setuptools=72.1.0=py39haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - vc=14.40=h2eaa2aa_1
  - vs2015_runtime=14.40.33807=h98bb1dd_1
  - wheel=0.44.0=py39haa95532_0
  - pip:
      - altair==5.4.1
      - annotated-types==0.7.0
      - attrs==24.2.0
      - blinker==1.9.0
      - branca==0.7.2
      - cachetools==5.5.0
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cmdstanpy==1.2.4
      - colorama==0.4.6
      - contourpy==1.3.0
      - cycler==0.12.1
      - flask==3.0.0
      - flask-cors==6.0.1
      - folium==0.17.0
      - fonttools==4.53.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.26.0
      - google-api-python-client==2.184.0
      - google-auth==2.41.1
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - grpcio==1.75.1
      - grpcio-status==1.71.2
      - gunicorn==21.2.0
      - holidays==0.57
      - httplib2==0.31.0
      - idna==3.10
      - importlib-metadata==8.7.0
      - importlib-resources==6.4.5
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - joblib==1.5.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - narwhals==1.8.1
      - numpy==2.0.2
      - packaging==24.1
      - pandas==2.1.3
      - patsy==1.0.1
      - pillow==10.4.0
      - plotly==5.18.0
      - prophet==1.1.5
      - proto-plus==1.26.1
      - protobuf==5.28.1
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.2
      - pydantic-core==2.41.4
      - pydeck==0.9.1
      - pygments==2.18.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.0
      - pytz==2024.2
      - referencing==0.35.1
      - requests==2.31.0
      - rich==13.8.1
      - rpds-py==0.20.0
      - rsa==4.9.1
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - six==1.16.0
      - smmap==5.0.1
      - stanio==0.5.1
      - statsmodels==0.14.5
      - streamlit==1.38.0
      - streamlit-folium==0.22.1
      - streamlit-javascript==0.1.5
      - tenacity==8.5.0
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - tornado==6.4.1
      - tqdm==4.66.5
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2024.1
      - uritemplate==4.2.0
      - urllib3==2.2.3
      - watchdog==4.0.2
      - werkzeug==3.1.3
      - xyzservices==2024.9.0
      - zipp==3.20.2
prefix: C:\Users\ashwi\anaconda\envs\agri
